name: laraevl APP
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laraevl
      DB_USERNAME: laraevl
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      MODULE_NAME: laraevl
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laraevl
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.3"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        shell: bash
        env:
          DB_DATABASE: laraevl
          DB_USERNAME: laraevl
          DB_PASSWORD: password
          BROADCAST_DRIVER: log
          CACHE_DRIVER: redis
          QUEUE_CONNECTION: redis
          SESSION_DRIVER: redis
          MODULE_NAME: laraevl
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            ./.scripts/deploy.sh